[32m2024-04-05 14:53:47 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 7bbbb067-f4dd-42a9-9da5-b969a68a8fa3 - 59861 - LOGS_CAPTURED - Started capturing logs in process (pid: 59861).
[32m2024-04-05 14:53:47 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 7bbbb067-f4dd-42a9-9da5-b969a68a8fa3 - 59861 - download_kaggle_data_2 - STEP_START - Started execution of step "download_kaggle_data_2".
[32m2024-04-05 14:53:48 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 7bbbb067-f4dd-42a9-9da5-b969a68a8fa3 - 59861 - download_kaggle_data_2 - STEP_FAILURE - Execution of step "download_kaggle_data_2" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "download_kaggle_data_2"::

IndexError: tuple index out of range

Stack Trace:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 464, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pranavkirti/Desktop/College/Spring 2024/CSE 314/314_final/314_final/assets.py", line 28, in download_kaggle_data_2
    kaggle.api.competition_download_files(competition_name, path=data_dir, force=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/kaggle/api/kaggle_api_extended.py", line 960, in competition_download_files
    url = response.retries.history[0].redirect_location.split('?')[0]
          ~~~~~~~~~~~~~~~~~~~~~~~~^^^
[0m
